version: '2'
services:
  nginx:
    build: ./docker/nginx
    ports:
     - ${DOCKER_NGINX_PORT}:80
    volumes:
     - ./:/var/www/api
    networks:
      appnet:
        aliases:
          - api.natureandsounds.local
  php:
    build: ./docker/php
    volumes:
     - ./:/var/www/api
    networks:
     - appnet
  redis:
    image: redis:alpine
    networks:
     - appnet
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DOCKER_DB_PORT}:3306
    volumes:
     - data:/var/lib/mysql
     - ./backups/db:/backups
    networks:
     - appnet
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
    volumes:
      - /sessions
    ports:
      - ${DOCKER_PHPMYADMIN_PORT}:80
    networks:
      - appnet
  newman:
    build: ./docker/newman
    tty: true
    volumes:
      - ./:/var/www/api
    networks:
      - appnet
networks:
  appnet:
    driver: "bridge"
volumes:
  data:
    driver: "local"
